PMS.DataInterface/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using PMS.DataInterface.EDMX;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using PMS.DataInterface.Globals;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PMS.DataInterface.Models;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json;

namespace PMS.DataInterface.Controllers
{

    public class UserManagementController : Controller
    {
        private RoleManager<IdentityRole> RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));
        private ApplicationUserManager _userManager;

        // GET: UserManagement
        public ActionResult Index()
        {
            return View();
        }

        // GET: Create User Step One
        [HttpGet]
        public ActionResult CreateUserStepOne()
        {
            List<string> resultRoles = new List<string>();
            List<string> resultMohafaza = new List<string>();
            List<string> resultKadaa = new List<string>();
            List<string> resultBalda = new List<string>();
            ViewBag.Services = getServices(null);

            using (WBI_PM_DEVEntities PMSPEntities = new WBI_PM_DEVEntities())
            {
                //Get Roles,Mohafaza,Kadaa,Balda And Store Them In ViewData -- Values Are Passed To The View
                resultRoles = PMSPEntities.GetRole(null).ToList<string>();
                ViewData["Roles"] = resultRoles.Select(tier => new SelectListItem { Text = tier.Trim(), Value = tier.Trim() }).ToList();

                resultMohafaza = PMSPEntities.GetMohafaza(null).ToList<string>();
                ViewData["Mohafaza"] = resultMohafaza.Select(tier => new SelectListItem { Text = tier.Trim(), Value = tier.Trim() }).ToList();

                resultKadaa = PMSPEntities.GetKadaa(null).ToList<string>();
                ViewData["Kadaa"] = resultKadaa.Select(tier => new SelectListItem { Text = tier.Trim(), Value = tier.Trim() }).ToList();

                resultBalda = PMSPEntities.GETBalda(null).ToList<string>();
                ViewData["Balda"] = resultBalda.Select(tier => new SelectListItem { Text = tier.Trim(), Value = tier.Trim() }).ToList();
            }

            var directorRole = RoleManager.FindByName("Director").Id;
            var managerRole = RoleManager.FindByName("Manager").Id;

            //var Directors = UserManager.Users.Where(u => u.Roles.Any(r => r.RoleId == directorRole)).ToList();
            //var Managers = UserManager.Users.Where(u => u.Roles.Any(r => r.RoleId == managerRole)).ToList();
            //List<IdentityUser> allManagerUsers = new List<IdentityUser>();
            //allManagerUsers.AddRange(Directors);
            //allManagerUsers.AddRange(Managers);
            //List<SelectListItem> ActionUsers = allManagerUsers.Select(x => new SelectListItem { Text = x.UserName, Value = x.Id }).ToList();
            //ViewData["ActionUsers"] = ActionUsers;

            var users = UserManager.Users.ToList();

            List<SelectListItem> AllUsers = users.Select(x => new SelectListItem { Text = x.UserName, Value = x.Id }).ToList();
            ViewData["AllUsers"] = AllUsers;



            return View();
        }

        // GET: Create User Step Two
        [HttpGet]
        public ActionResult CreateUserStepTwo()
        {
            var directorRole = RoleManager.FindByName("Director").Id;
            var managerRole = RoleManager.FindByName("Manager").Id;

            var Directors = UserManager.Users.Where(u => u.Roles.Any(r => r.RoleId == directorRole)).ToList();
            var Managers = UserManager.Users.Where(u => u.Roles.Any(r => r.RoleId == managerRole)).ToList();
            List<IdentityUser> allManagerUsers = new List<IdentityUser>();
            allManagerUsers.AddRange(Directors);
            allManagerUsers.AddRange(Managers);
            List<SelectListItem> ActionUsers = allManagerUsers.Select(x => new SelectListItem { Text = x.UserName, Value = x.Id }).ToList();
            ViewData["ActionUsers"] = ActionUsers;

            var users = UserManager.Users.ToList();

            List<SelectListItem> AllUsers = users.Select(x => new SelectListItem { Text = x.UserName, Value = x.Id }).ToList();
            ViewData["AllUsers"] = AllUsers;
            return View();
        }

        // GET: Create User Step Three
        [HttpGet]
        public ActionResult CreateUserStepThree()
        {
            return View();
        }

        [HttpGet]
        public JsonResult getJobDescription(string id, string SearchTerm)
        {
            List<string> result = new List<string>();

            using (WBI_PM_DEVEntities PMSPEntities = new WBI_PM_DEVEntities())
            {
                result = PMSPEntities.GetJobDescription(SearchTerm).ToList<string>();
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult getHash(string hash)
        {
            List<GetHashInfo_Result> result = new List<GetHashInfo_Result>();

            using (WBI_PM_DEVEntities PMSPEntities = new WBI_PM_DEVEntities())
            {
                result = PMSPEntities.GetHashInfo(hash).ToList<GetHashInfo_Result>();
            }
            result.Reverse();
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public List<string> getRoles()
        {
            List<string> result = new List<string>();

            using (WBI_PM_DEVEntities PMSPEntities = new WBI_PM_DEVEntities())
            {
                result = PMSPEntities.GetRole(null).ToList<string>();
            }

            return result;
        }

        [HttpGet]
        public string AssignIndividualsToUser(string UserName, string Hash)
        {
            //List<string> result = new List<string>();

            using (WBI_PM_DEVEntities PMSPEntities = new WBI_PM_DEVEntities())
            {
                //PMSPEntities.UserAss(Hash, UserName,"UserToIndividual");
            }

            return "Success";
        }

        [HttpGet]
        public string DeleteGroup(string groupname)
        {
            using (WBI_PM_DEVEntities PMSPEntities = new WBI_PM_DEVEntities())
            {
                PMSPEntities.GroupDelete(groupname);
            }

            return "Success";
        }

        [HttpGet]
        public string DeleteAction(string UserName, string ActionName, string From, string Description, string ForwardToUser, string Notify)
        {
            using (WBI_PM_DEVEntities PMSPEntities = new WBI_PM_DEVEntities())
            {
                PMSPEntities.UserByActionDelete(UserName, ActionName, Description, null, ForwardToUser, From, Notify);
            }

            return "Success";
        }


        [HttpGet]
        public string OwnerFieldAssign(string userName, string ownerColumn)
        {
            //List<string> result = new List<string>();

            using (WBI_PM_DEVEntities PMSPEntities = new WBI_PM_DEVEntities())
            {
                PMSPEntities.OwnerFieldsAss(ownerColumn , userName);
            }

            return "Success";
        }


        [HttpGet]
        public JsonResult CreateGroup(string createdBy, string GroupName, string Hash, string assignedToUser, string groupDescription = null)
        {
            try
            {
                using (WBI_PM_DEVEntities PMSPEntities = new WBI_PM_DEVEntities())
                {
                    List<GetGroupsAndUsers_Result> result = new List<GetGroupsAndUsers_Result>();


                    result = PMSPEntities.GetGroupsAndUsers(null, null).ToList<GetGroupsAndUsers_Result>();

                    GetGroupsAndUsers_Result groupNameExist = new GetGroupsAndUsers_Result();
                    groupNameExist = result.Where(x => x.Group == GroupName).FirstOrDefault();
                    if (groupNameExist != null)
                    {
                        return Json("Warning Group Name Exists!", JsonRequestBehavior.AllowGet);
                    }
                    Hash = Hash.Replace("_", " ");
                    if(!Hash.Contains("N''"))
                    {
                        Hash = Hash.Replace("'", "''");
                    }
                    PMSPEntities.UserAss(Hash, assignedToUser, "UserToIndividual", GroupName, groupDescription, 0, createdBy);
                    
                }
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }




          public string EditGroup(string oldgroupname, string newgroupname, string newgroupdesc)
        {          
                using (WBI_PM_DEVEntities PMSPEntities = new WBI_PM_DEVEntities())
                {
                List<GetGroupsAndUsers_Result> result = new List<GetGroupsAndUsers_Result>();

                result = PMSPEntities.GetGroupsAndUsers(null, null).ToList<GetGroupsAndUsers_Result>();
                if (oldgroupname != newgroupname)
                {
                    GetGroupsAndUsers_Result groupNameExist = new GetGroupsAndUsers_Result();
                    groupNameExist = result.Where(x => x.Group == newgroupname).FirstOrDefault();
                    if (groupNameExist != null)
                    {
                        
                        return ("Warning Group Name Exists!");

                    }
                }
                   

                PMSPEntities.GroupUpdate(newgroupname, newgroupdesc, oldgroupname,"");
                }
            return "Success";

        }

        [HttpGet]

PMS.DataInterface/Controllers/meftehsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PMS.DataInterface.EDMX;

namespace PMS.DataInterface.Controllers
{
    public class meftehsController : Controller
    {
        private Beirut1_WBEntities db = new Beirut1_WBEntities();

        // GET: meftehs
        public ActionResult Index()
        {
            return View(db.meftehs.ToList());
        }

        // GET: meftehs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mefteh mefteh = db.meftehs.Find(id);
            if (mefteh == null)
            {
                return HttpNotFound();
            }
            return View(mefteh);
        }

        // GET: meftehs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: meftehs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "mefteh_code,mefteh_name,meftef_phone")] mefteh mefteh)
        {
            if (ModelState.IsValid)
            {
                db.meftehs.Add(mefteh);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mefteh);
        }

        // GET: meftehs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mefteh mefteh = db.meftehs.Find(id);
            if (mefteh == null)
            {
                return HttpNotFound();
            }
            return View(mefteh);
        }

        // POST: meftehs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "mefteh_code,mefteh_name,meftef_phone")] mefteh mefteh)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mefteh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mefteh);
        }

        // GET: meftehs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mefteh mefteh = db.meftehs.Find(id);
            if (mefteh == null)
            {
                return HttpNotFound();
            }
            return View(mefteh);
        }

        // POST: meftehs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            mefteh mefteh = db.meftehs.Find(id);
            db.meftehs.Remove(mefteh);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PMS.DataInterface/Views/meftehs/Create.cshtml
@model PMS.DataInterface.EDMX.mefteh

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>mefteh</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.mefteh_code, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.mefteh_code, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.mefteh_code, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.mefteh_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.mefteh_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.mefteh_name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.meftef_phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.meftef_phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.meftef_phone, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index", "UserManagement")
    </div>
</body>
</html>

PMS.DataInterface/Views/meftehs/Delete.cshtml
@model PMS.DataInterface.EDMX.mefteh

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>mefteh</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.mefteh_name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.mefteh_name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.meftef_phone)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.meftef_phone)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index", "UserManagement")
            </div>
        }
    </div>
</body>
</html>

PMS.DataInterface/Views/meftehs/Details.cshtml
@model PMS.DataInterface.EDMX.mefteh

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>mefteh</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.mefteh_name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.mefteh_name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.meftef_phone)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.meftef_phone)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.mefteh_code }) |
        @Html.ActionLink("Back to List", "Index", "UserManagement")
    </p>
</body>
</html>

PMS.DataInterface/Views/meftehs/Edit.cshtml
@model PMS.DataInterface.EDMX.mefteh

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>mefteh</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.mefteh_code)
    
            <div class="form-group">
                @Html.LabelFor(model => model.mefteh_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.mefteh_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.mefteh_name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.meftef_phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.meftef_phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.meftef_phone, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index", "UserManagement")
    </div>
</body>
</html>

PMS.DataInterface/Views/meftehs/Index.cshtml
@model IEnumerable<PMS.DataInterface.EDMX.mefteh>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.mefteh_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.meftef_phone)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.mefteh_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.meftef_phone)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.mefteh_code }) |
                @*@Html.ActionLink("Details", "Details", new { id=item.mefteh_code }) |*@
                @Html.ActionLink("Delete", "Delete", new { id=item.mefteh_code })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>